[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/springboot.app-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/servicios"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
SPRING_PROFILES_ACTIVE = "prod"
SPRING_DATASOURCE_URL = "jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}"
SPRING_DATASOURCE_USERNAME = "${PGUSER}"
SPRING_DATASOURCE_PASSWORD = "${PGPASSWORD}"
SPRING_DATASOURCE_DRIVER_CLASS_NAME = "org.postgresql.Driver"
SPRING_JPA_DATABASE_PLATFORM = "org.hibernate.dialect.PostgreSQLDialect"
SPRING_JPA_HIBERNATE_DDL_AUTO = "update"
SPRING_JPA_SHOW_SQL = "false"
JWT_SECRET = "${JWT_SECRET}"
JWT_EXPIRATION = "86400000"
GOOGLE_CLIENT_ID = "${GOOGLE_CLIENT_ID}"
GOOGLE_CLIENT_SECRET = "${GOOGLE_CLIENT_SECRET}"
APP_GOOGLE_REDIRECT_URI = "${FRONTEND_URL}/auth/google/callback"
SPRING_MAIL_HOST = "${MAIL_HOST}"
SPRING_MAIL_PORT = "${MAIL_PORT}"
SPRING_MAIL_USERNAME = "${MAIL_USERNAME}"
SPRING_MAIL_PASSWORD = "${MAIL_PASSWORD}"
FRONTEND_URL = "${FRONTEND_URL}"
CORS_ALLOWED_ORIGINS = "${FRONTEND_URL},http://localhost:3000"
